// The 45 originally curated exercises with locally-hosted, visually verified start/end photos.
// Shared so the planning engine can treat them as trusted media too, not only the display layer.
export const localExerciseMedia: Record<string, [string, string]> = {
  "Sentadilla goblet": ["/exercises/goblet-squat-start.jpg", "/exercises/goblet-squat-end.jpg"],
  "Prensa de piernas": ["/exercises/leg-press-start.jpg", "/exercises/leg-press-end.jpg"],
  Sentadilla: ["/exercises/barbell-squat-start.jpg", "/exercises/barbell-squat-end.jpg"],
  "Press banca con mancuernas": ["/exercises/dumbbell-bench-press-start.jpg", "/exercises/dumbbell-bench-press-end.jpg"],
  "Press inclinado": ["/exercises/incline-bench-press-start.jpg", "/exercises/incline-bench-press-end.jpg"],
  "Press banca": ["/exercises/barbell-bench-press-start.jpg", "/exercises/barbell-bench-press-end.jpg"],
  "Jalon al pecho": ["/exercises/lat-pulldown-start.jpg", "/exercises/lat-pulldown-end.jpg"],
  "Remo con mancuerna": ["/exercises/dumbbell-row-start.jpg", "/exercises/dumbbell-row-end.jpg"],
  "Remo con barra": ["/exercises/barbell-row-start.jpg", "/exercises/barbell-row-end.jpg"],
  "Peso muerto rumano": ["/exercises/romanian-deadlift-start.jpg", "/exercises/romanian-deadlift-end.jpg"],
  Plancha: ["/exercises/plank-start.jpg", "/exercises/plank-end.jpg"],
  "Elevaciones laterales": ["/exercises/lateral-raise-start.jpg", "/exercises/lateral-raise-end.jpg"],
  "Curl femoral": ["/exercises/lying-leg-curl-start.jpg", "/exercises/lying-leg-curl-end.jpg"],
  "Press militar con mancuernas": ["/exercises/dumbbell-shoulder-press-start.jpg", "/exercises/dumbbell-shoulder-press-end.jpg"],
  "Pallof press": ["/exercises/pallof-press-start.jpg", "/exercises/pallof-press-end.jpg"],
  "Hip thrust": ["/exercises/barbell-hip-thrust-start.jpg", "/exercises/barbell-hip-thrust-end.jpg"],
  "Curl de biceps": ["/exercises/dumbbell-bicep-curl-start.jpg", "/exercises/dumbbell-bicep-curl-end.jpg"],
  Flexiones: ["/exercises/pushups-start.jpg", "/exercises/pushups-end.jpg"],
  "Aperturas en polea": ["/exercises/cable-flyes-start.jpg", "/exercises/cable-flyes-end.jpg"],
  "Fondos para pecho": ["/exercises/chest-dips-start.jpg", "/exercises/chest-dips-end.jpg"],
  Dominadas: ["/exercises/pullups-start.jpg", "/exercises/pullups-end.jpg"],
  "Remo sentado en polea": ["/exercises/seated-cable-row-start.jpg", "/exercises/seated-cable-row-end.jpg"],
  "Jalón de brazos rectos": ["/exercises/straight-arm-pulldown-start.jpg", "/exercises/straight-arm-pulldown-end.jpg"],
  "Face pull": ["/exercises/face-pull-start.jpg", "/exercises/face-pull-end.jpg"],
  "Pájaros con mancuernas": ["/exercises/rear-delt-fly-start.jpg", "/exercises/rear-delt-fly-end.jpg"],
  "Elevaciones frontales": ["/exercises/front-raise-start.jpg", "/exercises/front-raise-end.jpg"],
  "Curl con barra": ["/exercises/barbell-curl-start.jpg", "/exercises/barbell-curl-end.jpg"],
  "Curl martillo": ["/exercises/hammer-curl-start.jpg", "/exercises/hammer-curl-end.jpg"],
  "Curl predicador": ["/exercises/preacher-curl-start.jpg", "/exercises/preacher-curl-end.jpg"],
  "Fondos para tríceps": ["/exercises/triceps-dips-start.jpg", "/exercises/triceps-dips-end.jpg"],
  "Extensión de tríceps por encima de la cabeza": ["/exercises/overhead-triceps-extension-start.jpg", "/exercises/overhead-triceps-extension-end.jpg"],
  "Extensión de tríceps en polea": ["/exercises/triceps-pushdown-start.jpg", "/exercises/triceps-pushdown-end.jpg"],
  "Zancadas con barra": ["/exercises/barbell-lunge-start.jpg", "/exercises/barbell-lunge-end.jpg"],
  "Extensión de cuádriceps": ["/exercises/leg-extension-start.jpg", "/exercises/leg-extension-end.jpg"],
  "Sentadilla dividida con mancuernas": ["/exercises/dumbbell-split-squat-start.jpg", "/exercises/dumbbell-split-squat-end.jpg"],
  "Buenos días": ["/exercises/good-morning-start.jpg", "/exercises/good-morning-end.jpg"],
  "Puente de glúteos con barra": ["/exercises/barbell-glute-bridge-start.jpg", "/exercises/barbell-glute-bridge-end.jpg"],
  "Aducción de cadera en polea": ["/exercises/cable-hip-adduction-start.jpg", "/exercises/cable-hip-adduction-end.jpg"],
  "Crunch abdominal": ["/exercises/crunch-start.jpg", "/exercises/crunch-end.jpg"],
  "Elevación de piernas colgado": ["/exercises/hanging-leg-raise-start.jpg", "/exercises/hanging-leg-raise-end.jpg"],
  "Giros rusos en polea": ["/exercises/cable-russian-twist-start.jpg", "/exercises/cable-russian-twist-end.jpg"],
  "Crunch en polea": ["/exercises/cable-crunch-start.jpg", "/exercises/cable-crunch-end.jpg"],
  Hiperextensiones: ["/exercises/hyperextension-start.jpg", "/exercises/hyperextension-end.jpg"],
  "Elevación de gemelos de pie": ["/exercises/standing-calf-raise-start.jpg", "/exercises/standing-calf-raise-end.jpg"],
  "Elevación de gemelos sentado": ["/exercises/seated-calf-raise-start.jpg", "/exercises/seated-calf-raise-end.jpg"],
};

export const localExerciseNames = new Set(Object.keys(localExerciseMedia));
